### ISSUE TITLE
Retrieve checksum of a file

### ISSUE THREAD

**Issue by fibbo** [crs4/pydoop#116]
I didn't find it in the pydoop.hdfs API and I was wondering if it was planned to be implemented at some point.

And maybe this is the wrong place to ask but how does hadoop verify if a copy was successful? Does it compare checksums?

**Comment by simleo** [comment]
Since checksums are handled transparently by Hadoop, making them accessible to users has never been a priority for us. The Java API has `FileSystem.getFileChecksum`, so it should be relatively easy to add this functionality to the jpype backend. On the other hand, libhdfs does not wrap that method, so adding it to the native extension would require more work.

You're welcome to work on this if you want, and send us a pull request ;)
