### ISSUE TITLE
Avro I/O types = True

### ISSUE THREAD

**Issue by MariusDieck** [crs4/pydoop#157]
Hey,
i use pyavroc on my local PC and wanted to test it on hadoop. To get the maximum performance i use types = True. However pydoop uses dicts (which would be types =  False) and i am not sure if this is the only possibility or if there is a way to enable types = True in pydoop on hadoop.

Marius

**Comment by simleo** [comment]
When writing, you can already pass pyavroc objects instead of dictionaries. When reading, the `types` flag must be set, and this is currently not possible in pydoop. If you want to give it a try, it should only require a trivial change in `avrolib.py` (`AvroContext.__init__` could recognize a `pyavroc_types` kwarg and use it to set `types` in the deserializer)

**Comment by MariusDieck** [comment]
Mhh i tried it by directly putting types=True when the deserializer is called (just for testing) however this does not seem to change the performance at all (which is strange because without type=True it is much faster, 91444ms deserializing time when True, 91749 when using false). However thanks a lot :)

**Comment by simleo** [comment]
I've also run some tests and indeed overall performance seems virtually unaffected.
